// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type InvoiceInvoiceStatus string

const (
	InvoiceInvoiceStatusPENDING   InvoiceInvoiceStatus = "PENDING"
	InvoiceInvoiceStatusPAID      InvoiceInvoiceStatus = "PAID"
	InvoiceInvoiceStatusCANCELLED InvoiceInvoiceStatus = "CANCELLED"
)

func (e *InvoiceInvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceInvoiceStatus(s)
	case string:
		*e = InvoiceInvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceInvoiceStatus: %T", src)
	}
	return nil
}

type NullInvoiceInvoiceStatus struct {
	InvoiceInvoiceStatus InvoiceInvoiceStatus
	Valid                bool // Valid is true if InvoiceInvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceInvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceInvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceInvoiceStatus), nil
}

type InvoicePaymentMethod string

const (
	InvoicePaymentMethodCREDITCARD   InvoicePaymentMethod = "CREDIT_CARD"
	InvoicePaymentMethodBANKTRANSFER InvoicePaymentMethod = "BANK_TRANSFER"
	InvoicePaymentMethodPAYPAL       InvoicePaymentMethod = "PAYPAL"
)

func (e *InvoicePaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoicePaymentMethod(s)
	case string:
		*e = InvoicePaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoicePaymentMethod: %T", src)
	}
	return nil
}

type NullInvoicePaymentMethod struct {
	InvoicePaymentMethod InvoicePaymentMethod
	Valid                bool // Valid is true if InvoicePaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoicePaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.InvoicePaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoicePaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoicePaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoicePaymentMethod), nil
}

type InvoicePaymentStatus string

const (
	InvoicePaymentStatusPENDING   InvoicePaymentStatus = "PENDING"
	InvoicePaymentStatusCOMPLETED InvoicePaymentStatus = "COMPLETED"
	InvoicePaymentStatusFAILED    InvoicePaymentStatus = "FAILED"
)

func (e *InvoicePaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoicePaymentStatus(s)
	case string:
		*e = InvoicePaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoicePaymentStatus: %T", src)
	}
	return nil
}

type NullInvoicePaymentStatus struct {
	InvoicePaymentStatus InvoicePaymentStatus
	Valid                bool // Valid is true if InvoicePaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoicePaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoicePaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoicePaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoicePaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoicePaymentStatus), nil
}

type TicketTicketPriority string

const (
	TicketTicketPriorityLOW      TicketTicketPriority = "LOW"
	TicketTicketPriorityMEDIUM   TicketTicketPriority = "MEDIUM"
	TicketTicketPriorityHIGH     TicketTicketPriority = "HIGH"
	TicketTicketPriorityURGENT   TicketTicketPriority = "URGENT"
	TicketTicketPriorityCRITICAL TicketTicketPriority = "CRITICAL"
)

func (e *TicketTicketPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketTicketPriority(s)
	case string:
		*e = TicketTicketPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketTicketPriority: %T", src)
	}
	return nil
}

type NullTicketTicketPriority struct {
	TicketTicketPriority TicketTicketPriority
	Valid                bool // Valid is true if TicketTicketPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketTicketPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TicketTicketPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketTicketPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketTicketPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketTicketPriority), nil
}

type TicketTicketStatus string

const (
	TicketTicketStatusOPEN       TicketTicketStatus = "OPEN"
	TicketTicketStatusINPROGRESS TicketTicketStatus = "IN_PROGRESS"
	TicketTicketStatusRESOLVED   TicketTicketStatus = "RESOLVED"
	TicketTicketStatusCLOSED     TicketTicketStatus = "CLOSED"
	TicketTicketStatusREOPENED   TicketTicketStatus = "REOPENED"
)

func (e *TicketTicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketTicketStatus(s)
	case string:
		*e = TicketTicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketTicketStatus: %T", src)
	}
	return nil
}

type NullTicketTicketStatus struct {
	TicketTicketStatus TicketTicketStatus
	Valid              bool // Valid is true if TicketTicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketTicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketTicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketTicketStatus), nil
}

type UserRole string

const (
	UserRoleAdmin      UserRole = "Admin"
	UserRoleTechnician UserRole = "Technician"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Customer struct {
	ID         pgtype.UUID
	LastName   string
	FirstName  string
	Username   string
	Email      pgtype.Text
	Password   string
	IsVerified pgtype.Bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type InvoiceInvoice struct {
	ID        pgtype.UUID
	TicketID  pgtype.UUID
	Amount    pgtype.Numeric
	Currency  string
	Status    NullInvoiceInvoiceStatus
	DueDate   pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type InvoicePayment struct {
	ID          pgtype.UUID
	InvoiceID   pgtype.UUID
	Amount      pgtype.Numeric
	PaymentDate pgtype.Timestamptz
	Method      NullInvoicePaymentMethod
	Status      NullInvoicePaymentStatus
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TenantTenant struct {
	ID         pgtype.UUID
	TenantName string
	Domain     string
	Email      string
	IsActive   pgtype.Bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type TenantTenantUser struct {
	TenantID pgtype.UUID
	UserID   pgtype.UUID
}

type TicketComment struct {
	ID        pgtype.UUID
	TicketID  pgtype.UUID
	Comment   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TicketTicket struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	CustomerID  pgtype.UUID
	AssignedTo  pgtype.UUID
	Title       string
	Description pgtype.Text
	Status      NullTicketTicketStatus
	Priority    NullTicketTicketPriority
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ClosedAt    pgtype.Timestamptz
}

type User struct {
	ID         pgtype.UUID
	Username   string
	Email      string
	Password   string
	Role       UserRole
	IsActive   pgtype.Bool
	IsVerified pgtype.Bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}
