apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: task-app
data:
  APP_ENV: "production"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "task"
  DB_USERNAME: "task"
  DB_SSLMODE: "disable"
  LOG_LEVEL: "info"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000"
  PORT: "8080"